version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 99
  reviewers:
  - AravindVNair99
  assignees:
  - AravindVNair99
  ignore:
  - dependency-name: express-rate-limit
    versions:
    - 5.2.3
    - 5.2.5
    - 5.2.6
