version: 1
update_configs:
  - package_manager: "javascript"
<<<<<<< HEAD
<<<<<<< HEAD
    directory: "/"
=======
    directory: "/functions"
>>>>>>> Add Dependabot
=======
    directory: "/"
>>>>>>> Fixes #13
    update_schedule: "live"
    default_reviewers:
      - "AravindVNair99"
    default_assignees:
      - "AravindVNair99"
