version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/functions"
    update_schedule: "live"
    default_reviewers:
      - "AravindVNair99"
    default_assignees:
      - "AravindVNair99"
